import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button } from "../components/Button";
import { Cards } from "../components/Cards";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <main>
        <div
        className={styles.main}
          style={{
            maxWidth: "460px",
            display: "flex",
            flexDirection: "column",
            gap: "40px",
            justifyContent: "center",
          }}
        >
          <h1>Maximize skill, minimize budget</h1>
          <p>
            Our modern courses across a range of in-demand skills will give you
            the knowledge you need to live the life you want.
          </p>
          <div>
            <Button text="Get Started" background="gradient-pink" />
          </div>
          <div
            className={styles.highlightedImageDesktop}
            style={{
              position: "absolute",
              right: "-150px",
              top: "-150px",
              zIndex: "1",
            }}
          >
            <Image
              src="/main.webp"
              alt="main-image"
              width={1050}
              height={1000}
              quality={100}
            />
          </div>
        </div>
        <div className={styles.highlightedImageMobile}>
          <Image src="/main-mobile.webp" alt="main-image" layout="fill" />
        </div>
        <Cards />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
